eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    com:
      iot:
        business:
          dao: trace
    root: info
  pattern:
    console: "'%p%m%n'"
server:
  port: 9005
  servlet:
    context-path: /web
spring:
  application:
    name: web
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/iotdb?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          username: ${MYSQL_USER}
          password: ${MYSQL_PASSWORD}


    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 60000
      maximum-pool-size: 50
      minimum-idle: 10
  devtools:
    restart:
      enabled: true
  redis:
    # 地址
    host: ${REDIS_HOST}
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ${REDIS_PASSWORD}
    timeout: 10000
  rabbitmq:
    ####连接地址
    host: ${RABBITMQ_HOST}
    ####端口号
    port: 5672
    ####账号
    username: ${RABBITMQ_USER}
    ####密码
    password: ${RABBITMQ_PASSWORD}
    ## 心跳  请求的心跳超时，以秒为单位； 零表示没有
    requested-heartbeat: 40
    ####心跳开启
    keepalive: true
    ### 地址
    virtual-host: ${RABBITMQ_VHOST}
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 1
          ####重试间隔时间
          initial-interval: 3000
        acknowledge-mode: auto

# MyBatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

wx:
  mp:
#    useRedis: false
#    redisConfig:
#      host: 127.0.0.1
#      port: 6379
    configs:
      - appId: wxe8338ad8db225d43 # 第一个公众号的appid
        secret: ef2eb35470de83d181c3907486e504ae # 公众号的appsecret
        token: shiyaniotlink # 接口配置里的Token值
#        aesKey: 111 # 接口配置里的EncodingAESKey值